name: dfa_media
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_gen: ^5.6.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  build_runner: ^2.0.0
  flutter_gen_runner: ^5.0.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Stolzl
      fonts:
        - asset: assets/fonts/stolzl_regular.otf