name: dfa_media
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_gen: ^5.6.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Stolzl
      fonts:
        - asset: assets/fonts/Stolzl-Regular.ttf
        - asset: assets/fonts/Stolzl-Medium.ttf
          weight: 500
        - asset: assets/fonts/Stolzl-Bold.ttf
          weight: 700
